### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [GilesStrong/lumin#32]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.1. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary lumin -w /tmp/ext lumin==0.5.1
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting lumin==0.5.1
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/561/5d2232da9ea91/lumin-0.5.1.tar.gz (116 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-2nqqp23z/lumin/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-2nqqp23z/lumin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-2nqqp23z/lumin/pip-egg-info
         cwd: /tmp/pip-wheel-2nqqp23z/lumin/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-2nqqp23z/lumin/setup.py", line 9, in <module>
        with open('requirements.txt') as f: requirements = f.read().strip().split('\n')
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by GilesStrong** [comment]
Hi! Thanks for bringing this to my attention (and indeed for checking out Lumin). I'll aim to fix this in the next release.
In the meantime, the requirements file may be found here: https://github.com/GilesStrong/lumin/blob/v0.5.1/requirements.txt

Alternatively, the package may be installed via pip `pip install lumin==0.5.1`. If this method of installation isn't feasible, could you let me know why, or what your particular use case is? This way I can better understand user needs and offer alternative installation methods to save them from having to build the package themselves.
Cheers!

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

**Comment by GilesStrong** [comment]
Ah I see. I wasn't aware of that, and thank you very much for taking time to provide a fix for it!
I'll merge your PR now.
